swagger: "2.0"
info:
  version: "0.0.1"
  title: Goals App Api
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /goals:
    # our controller name
    x-swagger-router-controller: goals
    get:
      description: get the goals list
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetGoalsListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: add a new goal to the list
      # goal info to be stored
      parameters:
        - name: title
          description: Goal description
          in: body
          required: true
          schema:
            $ref: "#/definitions/Goal"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /goals/{id}:
    # our controller name
    x-swagger-router-controller: goal
    get:
      description: get a goal
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetGoalResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: update a goal
      # define the parameters
      parameters:
        - name: id
          description: Goal id
          type: string
          in: path
          required: true
        - name: title
          description: Goal properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Goal"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: delete a goal
      # define the parameters
      parameters:
        - name: id
          description: Goal id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetGoalsListResponse:
    required:
      - goals
    properties:
      # The array of goals
      goals:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            title:
              type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GetGoalResponse:
    required:
      - id
      - title
    properties:
      id:
        type: string
      title: 
        type: string
  Goal:
    type: object
    properties:
      title:
        type: string
        description: task object name
    required:
      - title
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
